language: node_js

node_js:
- 0.10

after_success:
- CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate < ./coverage/lcov.info

deploy:
  provider: npm
  api_key: $NPM_API_KEY
  email: thaiat@ipelia.com
  on:
    tags: true
    all_branches: true
    repo: thaiat/gulp-mux